matrix:
- name: markdown
  dictionary:
    wordlists:
      - spellcheck-wordlist.txt
    output: spellspeck-wordlist.dic
    encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
    - pyspelling.filters.html:
        comments: false
        attributes:
        - title
        - alt
        ignores:
        - code
        - pre
  sources:
    - 'packages/sage-react/lib/*/*.*'
  default_encoding: utf-8
