version: "3.4"

services:
  router:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  lerna:
    user: node
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        yarn install --check-files
        yarn bootstrap
        yarn build
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules
      - ./packages/sage-packs/node_modules:/app/packages/sage-packs/node_modules
      - ./packages/sage-assets/node_modules:/app/packages/sage-assets/node_modules
      - ./packages/sage-react/node_modules:/app/packages/sage-react/node_modules
      - ./packages/sage-system/node_modules:/app/packages/sage-system/node_modules
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile.dev
      target: base
    working_dir: "/app/docs"
    command:
      - /bin/bash
      - -c
      - |
        yarn install --check-files
        bundle check || bundle install --jobs 8
        yarn start
    ports:
      - "4000:4000"
      - "4035:4035"
    depends_on:
      - router
      - lerna
    volumes:
      - ".:/app:delegated"
      - "./docs/node_modules:/app/docs/node_modules"
      - "./docs/tmp:/app/docs/tmp"
