version: "3.4"

x-npm-common: &npm-common
  build:
    context: .
    dockerfile: docker/Dockerfile.dev
    target: base
  working_dir: /app
  command:
    - /bin/bash
    - -c
    - |
      yarn install --check-files
      yarn build:watch

services:
  router:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
  npm_assets:
    <<: *npm-common
    volumes:
      - ./packages/sage-assets:/app:delegated
      - ./packages/sage-assets/node_modules:/app/node_modules
  npm_react:
    <<: *npm-common
    volumes:
      - ./packages/sage-react:/app:delegated
      - ./packages/sage-react/node_modules:/app/node_modules
  npm_system:
    <<: *npm-common
    volumes:
      - ./packages/sage-system:/app:delegated
      - ./packages/sage-system/node_modules:/app/node_modules
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile.dev
      target: base
    working_dir: "/app/docs"
    command:
      - /bin/bash
      - -c
      - |
        yarn install --check-files
        bundle check || bundle install --jobs 8
        yarn start
    ports:
      - "4000:4000"
      - "4035:4035"
    depends_on:
      - router
      - npm_assets
      - npm_react
      - npm_system
    volumes:
      - ".:/app:delegated"
      - "./docs/node_modules:/app/docs/node_modules"
      - "./docs/tmp:/app/docs/tmp"
