version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  lint:
    executor:
      name: node/default
    docker:
      - image: circleci/node:latest-browsers
    resource_class: small
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
release:
  docker:
    - image: circleci/node
  resource_class: small
  steps:
    - checkout
    - node/with-cache:
        steps:
          - add_ssh_keys:
              fingerprints:
                - '0a:4d:3f:bd:33:18:a3:42:24:6a:8f:39:3e:e0:70:ca'
          - run: npx lerna bootstrap --hoist --ci
          - run: npx lerna version --conventional-commits --create-release github --yes
workflows:
  sage_system_specs:
    jobs:
      - lint
      - release:
        filters:
          branches:
            only: master
          requires:
            - lint
