version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint-and-build:
    executor:
      name: node/default
    docker:
      - image: circleci/ruby:2.4.9-node
    resource_class: small
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm config set '//npm.pkg.github.com/:_authToken' '${GH_TOKEN}'
            - run: yarn install
            - run: yarn lint
            - run: yarn build
  release:
      docker:
        - image: circleci/ruby:2.4.9-node
      resource_class: small
      steps:
        - checkout
        - ruby/install:
            version: '2.4.9'
        - node/with-cache:
            steps:
              - add_ssh_keys:
                  fingerprints:
                    - "0a:4d:3f:bd:33:18:a3:42:24:6a:8f:39:3e:e0:70:ca"
              - run: npm config set '//npm.pkg.github.com/:_authToken' '${GH_TOKEN}'
              - run: git config user.email "dev+github-bot@kajabi.com"
              - run: git config user.name "Kajabi Automation Bot"
              - run: (cd docs && bundle install)
              - run: ./bin/tag-gem.sh
              - run: npx lerna bootstrap --ci
              - run: npx lerna publish --registry github --yes

workflows:
    lint-and-build:
      jobs:
        - lint-and-build
        - release:
            filters:
              branches:
                only: master
            requires:
              - lint-and-build
