version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-lint:
    executor:
      name: node/default
    docker:
      - image: circleci/node:latest-browsers
    resource_class: small
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
  release:
      docker:
        - image: circleci/node
      resource_class: small
      steps:
        - checkout
        - node/with-cache:
            steps:
              - add_ssh_keys:
                  fingerprints:
                    - "0a:4d:3f:bd:33:18:a3:42:24:6a:8f:39:3e:e0:70:ca"
              - run: yarn build
              - run: git config user.email "dev+github-bot@kajabi.com"
              - run: git config user.name "Kajabi Automation Bot"
              - run: npx lerna bootstrap --ci
              - run: npx lerna version --no-private --conventional-commits --create-release github --yes
              - run: npx lerna publish --registry github --yes

workflows:
    build-and-lint:
      jobs:
        - build-and-lint
        - release:
            filters:
              branches:
                only: master
            requires:
              - build-and-lint
