name: Lint-Test-Build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint_test_build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sage-Lib Repo
        uses: "actions/checkout@v2"

      - name: Clone Sage-Lib Repo
        uses: "actions/setup-node@v2"
        with:
          node-version: "14"
      - run: npm install
      - run: npm test

      - name: Yarn Install
        run: yarn install

      - name: Yarn Lint
        run: yarn lint

      - name: Yarn Test
        run: yarn test

      - name: Yarn Build
        run: yarn build
