name: Release-Deploy
on:
  # !!Emergency override!! uncomment the below and access the actions tab in GitHub
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release_deploy:
    name: Release and Deploy
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.4.9-node
    steps:
      # Setup Auth token to push to github packages
      - name: Set NPM Config
        run: npm config set '//npm.pkg.github.com/:_authToken' '${{ secrets.ACCESS_TOKEN }}'

      - name: Clone Sage-Lib Repo
        uses: actions/checkout@v2

      # Setup Git Credentials to come from the Bot
      - name: Set Bot Email
        run: git config user.email "dev+github-bot@kajabi.com"

      - name: Set Bot Name
        run: git config user.name "Kajabi Automation Bot"

      # Install/Lint/Test/Build
      - name: Yarn Install
        run: yarn install

      - name: Yarn Lint
        run: yarn lint

      - name: Yarn Test
        run: yarn test

      - name: Yarn Build
        run: yarn build

      # Lerna Bootstrap and Publish package
      - name: Lerna Bootstrap
        run: npx lerna bootstrap --ci

      - name: Lerna Publish
        run: npx lerna publish --registry github --yes

      # Deploy site
      - name: Documentation Site Deploy
        run: yarn docs:deploy

      - name: Storybook Site Deploy
        run: yarn storybook:deploy

      - name: SassDocs Site Deploy
        run: yarn sassdocs:deploy
