# This is workflow for spell checking using PySpelling lib (https://pypi.org/project/pyspelling/)
name: Spell-Check
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  run_spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Run spell check
